import type { Campaign } from "../db/schema/campaigns";

const now = new Date().toISOString();

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp_marinade",
    projectId: "prj_marinade",
    slug: "marinade-first-stake",
    title: "10k SOL stakers wanted",
    hook: "Stake once. Unlock liquid SOL rewards.",
    description: "Complete a stake action and claim from escrow.",
    objective: "activation",
    status: "active",
    priority: "contract",
    zones: ["discover", "journey"],
    category: "staking",
    budgetLamports: 50_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 5_000_000,
    maxCompletions: 10_000,
    completionCount: 0,
    weight: 10,
    tasks: [
      {
        id: "t_visit",
        type: "visit",
        title: "Visit Marinade",
        description: "Open the staking app",
        rewardLamports: 1_000_000,
      },
      {
        id: "t_stake",
        type: "stake",
        title: "Stake SOL",
        description: "Confirm stake tx — Helius verifies",
        rewardLamports: 5_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cmp_jupiter",
    projectId: "prj_jupiter",
    slug: "jupiter-first-swap",
    title: "Swap once on Jupiter",
    hook: "1 swap. Real route. Real reward.",
    description: "Execute any swap; submit signature for Helius proof.",
    objective: "activation",
    status: "active",
    priority: "contract",
    zones: ["discover"],
    category: "defi",
    budgetLamports: 30_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 3_000_000,
    maxCompletions: 8_000,
    completionCount: 0,
    weight: 8,
    tasks: [
      {
        id: "t_swap",
        type: "swap",
        title: "Complete a swap",
        description: "Any Jupiter route — Helius must confirm",
        rewardLamports: 3_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cmp_onboard",
    projectId: "prj_swan",
    slug: "swan-onboarding",
    title: "Learn Solana in 5 minutes",
    hook: "New to Solana? Start here.",
    description: "Override-priority onboarding campaign.",
    objective: "education",
    status: "active",
    priority: "override",
    zones: ["journey", "discover"],
    category: "education",
    budgetLamports: 10_000_000_000,
    spentLamports: 0,
    rewardPerCompletionLamports: 2_000_000,
    maxCompletions: 50_000,
    completionCount: 0,
    weight: 20,
    tasks: [
      {
        id: "t_quiz",
        type: "quiz",
        title: "Solana basics quiz",
        description: "Pass the short orientation",
        rewardLamports: 2_000_000,
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];
